---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msilver-test-pvc
  labels:
    username: msilver
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi

