---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msilver-test-app
  labels:
    app: msilver-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msilver-test-app
  template:
    metadata:
      labels:
        app: msilver-test-app
    spec:
      containers:
        - name: msilver-test-redis
          image: redis:7
          volumeMounts:
          - name: msilver-test-pvc
            mountPath: "/data"
      volumes:
      - name: msilver-test-pvc
        persistentVolumeClaim:
          claimName: msilver-test-pvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msilver-test-app
  template:
    metadata:
      labels:
        app: msilver-test-app
    spec:
      containers:
        - name: msilver-test-flask
          imagePullPolicy: Always
          image: silvermadison/gene_api:1.0
          env:
          - name: FLASK_APP
            value: "gene_api.py"
          ports:
          - name: http
            containerPort: 5000

