---
apiVersion: v1
kind: Service
metadata:
  name: msilver-test-flask
spec:
  type: ClusterIP
  selector:
    app: msilver-test-app
  ports:
  - name: msilver-test-flask
    port: 5000
    targetPort: 5000

